// ─────────────────────────────────────────────────────────────
// OWGR snapshot — auto-generated. DO NOT hand-edit the array below.
// Source: apiweb.owgr.com getRankings · ranking week ending 17 May 2026
// Seeded 2026-06-05. Refresh once on Mon 15 Jun 2026, then frozen.
// ─────────────────────────────────────────────────────────────
export const OWGR_AS_OF = "17 May 2026";

export const OWGR_RANKINGS = [
  { rank: 1, name: "Scottie Scheffler", country: "US", flag: "🇺🇸" },
  { rank: 2, name: "Rory McIlroy", country: "NIR", flag: "🇬🇧" },
  { rank: 3, name: "Cameron Young", country: "US", flag: "🇺🇸" },
  { rank: 4, name: "Matt Fitzpatrick", country: "ENG", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { rank: 5, name: "Justin Rose", country: "ENG", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { rank: 6, name: "Collin Morikawa", country: "US", flag: "🇺🇸" },
  { rank: 7, name: "Tommy Fleetwood", country: "ENG", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { rank: 8, name: "Xander Schauffele", country: "US", flag: "🇺🇸" },
  { rank: 9, name: "J.J. Spaun", country: "US", flag: "🇺🇸" },
  { rank: 10, name: "Chris Gotterup", country: "US", flag: "🇺🇸" },
  { rank: 11, name: "Russell Henley", country: "US", flag: "🇺🇸" },
  { rank: 12, name: "Jon Rahm", country: "ES", flag: "🇪🇸" },
  { rank: 13, name: "Ludvig Aberg", country: "SE", flag: "🇸🇪" },
  { rank: 14, name: "Robert MacIntyre", country: "SCO", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  { rank: 15, name: "Aaron Rai", country: "ENG", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { rank: 16, name: "Justin Thomas", country: "US", flag: "🇺🇸" },
  { rank: 17, name: "Ben Griffin", country: "US", flag: "🇺🇸" },
  { rank: 18, name: "Sepp Straka", country: "AT", flag: "🇦🇹" },
  { rank: 19, name: "Hideki Matsuyama", country: "JP", flag: "🇯🇵" },
  { rank: 20, name: "Alex Noren", country: "SE", flag: "🇸🇪" },
  { rank: 21, name: "Patrick Reed", country: "US", flag: "🇺🇸" },
  { rank: 22, name: "Harris English", country: "US", flag: "🇺🇸" },
  { rank: 23, name: "Jacob Bridgeman", country: "US", flag: "🇺🇸" },
  { rank: 24, name: "Si Woo Kim", country: "KR", flag: "🇰🇷" },
  { rank: 25, name: "Kristoffer Reitan", country: "NO", flag: "🇳🇴" },
  { rank: 26, name: "Akshay Bhatia", country: "US", flag: "🇺🇸" },
  { rank: 27, name: "Tyrrell Hatton", country: "ENG", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { rank: 28, name: "Nicolai Hojgaard", country: "DK", flag: "🇩🇰" },
  { rank: 29, name: "Kurt Kitayama", country: "US", flag: "🇺🇸" },
  { rank: 30, name: "Viktor Hovland", country: "NO", flag: "🇳🇴" },
  { rank: 31, name: "Min Woo Lee", country: "AU", flag: "🇦🇺" },
  { rank: 32, name: "Bryson DeChambeau", country: "US", flag: "🇺🇸" },
  { rank: 33, name: "Patrick Cantlay", country: "US", flag: "🇺🇸" },
  { rank: 34, name: "Maverick McNealy", country: "US", flag: "🇺🇸" },
  { rank: 35, name: "Sam Burns", country: "US", flag: "🇺🇸" },
  { rank: 36, name: "Keegan Bradley", country: "US", flag: "🇺🇸" },
  { rank: 37, name: "Ryan Gerard", country: "US", flag: "🇺🇸" },
  { rank: 38, name: "Rickie Fowler", country: "US", flag: "🇺🇸" },
  { rank: 39, name: "Jake Knapp", country: "US", flag: "🇺🇸" },
  { rank: 40, name: "Shane Lowry", country: "IE", flag: "🇮🇪" },
  { rank: 41, name: "Jason Day", country: "AU", flag: "🇦🇺" },
  { rank: 42, name: "Alex Smalley", country: "US", flag: "🇺🇸" },
  { rank: 43, name: "Marco Penge", country: "ENG", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { rank: 44, name: "Daniel Berger", country: "US", flag: "🇺🇸" },
  { rank: 45, name: "Michael Kim", country: "US", flag: "🇺🇸" },
  { rank: 46, name: "Matt McCarty", country: "US", flag: "🇺🇸" },
  { rank: 47, name: "Jordan Spieth", country: "US", flag: "🇺🇸" },
  { rank: 48, name: "Gary Woodland", country: "US", flag: "🇺🇸" },
  { rank: 49, name: "Adam Scott", country: "AU", flag: "🇦🇺" },
  { rank: 50, name: "Nicolas Echavarria", country: "CO", flag: "🇨🇴" },
  { rank: 51, name: "Samuel Stevens", country: "US", flag: "🇺🇸" },
  { rank: 52, name: "Corey Conners", country: "CA", flag: "🇨🇦" },
  { rank: 53, name: "Andrew Novak", country: "US", flag: "🇺🇸" },
  { rank: 54, name: "Ryan Fox", country: "NZ", flag: "🇳🇿" },
  { rank: 55, name: "Brian Harman", country: "US", flag: "🇺🇸" },
  { rank: 56, name: "Michael Brennan", country: "US", flag: "🇺🇸" },
  { rank: 57, name: "Pierceson Coody", country: "US", flag: "🇺🇸" },
  { rank: 58, name: "David Puig", country: "ES", flag: "🇪🇸" },
  { rank: 59, name: "Nick Taylor", country: "CA", flag: "🇨🇦" },
  { rank: 60, name: "Ryo Hisatsune", country: "JP", flag: "🇯🇵" },
  { rank: 61, name: "Harry Hall", country: "ENG", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { rank: 62, name: "Sami Valimaki", country: "FI", flag: "🇫🇮" },
  { rank: 63, name: "Max Greyserman", country: "US", flag: "🇺🇸" },
  { rank: 64, name: "Thomas Detry", country: "BE", flag: "🇧🇪" },
  { rank: 65, name: "Matti Schmid", country: "DE", flag: "🇩🇪" },
  { rank: 66, name: "Bud Cauley", country: "US", flag: "🇺🇸" },
  { rank: 67, name: "Rasmus Hojgaard", country: "DK", flag: "🇩🇰" },
  { rank: 68, name: "Jayden Schaper", country: "ZA", flag: "🇿🇦" },
  { rank: 69, name: "Matt Wallace", country: "ENG", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { rank: 70, name: "Michael Thorbjornsen", country: "US", flag: "🇺🇸" },
  { rank: 71, name: "Jordan Smith", country: "ENG", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { rank: 72, name: "Sungjae Im", country: "KR", flag: "🇰🇷" },
  { rank: 73, name: "Casey Jarvis", country: "ZA", flag: "🇿🇦" },
  { rank: 74, name: "Aldrich Potgieter", country: "ZA", flag: "🇿🇦" },
  { rank: 75, name: "Wyndham Clark", country: "US", flag: "🇺🇸" },
  { rank: 76, name: "Patrick Rodgers", country: "US", flag: "🇺🇸" },
  { rank: 77, name: "John Keefer", country: "US", flag: "🇺🇸" },
  { rank: 78, name: "Sahith Theegala", country: "US", flag: "🇺🇸" },
  { rank: 79, name: "Rasmus Neergaard-Petersen", country: "DK", flag: "🇩🇰" },
  { rank: 80, name: "Haotong Li", country: "CN", flag: "🇨🇳" },
  { rank: 81, name: "Andrew Putnam", country: "US", flag: "🇺🇸" },
  { rank: 82, name: "Taylor Pendrith", country: "CA", flag: "🇨🇦" },
  { rank: 83, name: "Alex Fitzpatrick", country: "ENG", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { rank: 84, name: "Max McGreevy", country: "US", flag: "🇺🇸" },
  { rank: 85, name: "J.T. Poston", country: "US", flag: "🇺🇸" },
  { rank: 86, name: "John Parry", country: "ENG", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { rank: 87, name: "Austin Smotherman", country: "US", flag: "🇺🇸" },
  { rank: 88, name: "Christiaan Bezuidenhout", country: "ZA", flag: "🇿🇦" },
  { rank: 89, name: "Richard Hoey", country: "PH", flag: "🇵🇭" },
  { rank: 90, name: "Lucas Herbert", country: "AU", flag: "🇦🇺" },
  { rank: 91, name: "Daniel Hillier", country: "NZ", flag: "🇳🇿" },
  { rank: 92, name: "Ricky Castillo", country: "US", flag: "🇺🇸" },
  { rank: 93, name: "Stephan Jaeger", country: "DE", flag: "🇩🇪" },
  { rank: 94, name: "Garrick Higgo", country: "ZA", flag: "🇿🇦" },
  { rank: 95, name: "David Lipsky", country: "US", flag: "🇺🇸" },
  { rank: 96, name: "Chris Kirk", country: "US", flag: "🇺🇸" },
  { rank: 97, name: "Lucas Glover", country: "US", flag: "🇺🇸" },
  { rank: 98, name: "Denny McCarthy", country: "US", flag: "🇺🇸" },
  { rank: 99, name: "Shaun Norris", country: "ZA", flag: "🇿🇦" },
  { rank: 100, name: "Elvis Smylie", country: "AU", flag: "🇦🇺" },
  { rank: 103, name: "Tony Finau", country: "US", flag: "🇺🇸" },
  { rank: 104, name: "Blades Brown", country: "US", flag: "🇺🇸" },
  { rank: 105, name: "Brooks Koepka", country: "US", flag: "🇺🇸" },
  { rank: 106, name: "Adrien Saddier", country: "FR", flag: "🇫🇷" },
  { rank: 107, name: "Sudarshan Yellamaraju", country: "CA", flag: "🇨🇦" },
  { rank: 108, name: "McClure Meissner", country: "US", flag: "🇺🇸" },
  { rank: 109, name: "Daniel Brown(Oct1994)", country: "ENG", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { rank: 110, name: "Chandler Blanchet", country: "US", flag: "🇺🇸" },
  { rank: 111, name: "Brian Campbell", country: "US", flag: "🇺🇸" },
  { rank: 112, name: "Andy Sullivan", country: "ENG", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { rank: 113, name: "Doc Redman", country: "US", flag: "🇺🇸" },
  { rank: 114, name: "Mark Hubbard", country: "US", flag: "🇺🇸" },
  { rank: 115, name: "Emiliano Grillo", country: "AR", flag: "🇦🇷" },
  { rank: 116, name: "Angel Ayora", country: "ES", flag: "🇪🇸" },
  { rank: 117, name: "Eric Cole", country: "US", flag: "🇺🇸" },
  { rank: 118, name: "Richard Sterne", country: "ZA", flag: "🇿🇦" },
  { rank: 119, name: "Jose Luis Ballester", country: "ES", flag: "🇪🇸" },
  { rank: 120, name: "Jacob Skov Olesen", country: "DK", flag: "🇩🇰" },
  { rank: 121, name: "Thorbjorn Olesen", country: "DK", flag: "🇩🇰" },
  { rank: 122, name: "Chun-an Yu", country: "TW", flag: "🇹🇼" },
  { rank: 123, name: "Max Homa", country: "US", flag: "🇺🇸" },
  { rank: 124, name: "Tom McKibbin", country: "NIR", flag: "🇬🇧" },
  { rank: 125, name: "Kevin Roy", country: "US", flag: "🇺🇸" },
  { rank: 126, name: "Ian Holt", country: "US", flag: "🇺🇸" },
  { rank: 127, name: "Mikael Lindberg", country: "SE", flag: "🇸🇪" },
  { rank: 128, name: "Thriston Lawrence", country: "ZA", flag: "🇿🇦" },
  { rank: 129, name: "Eugenio Chacarra", country: "ES", flag: "🇪🇸" },
  { rank: 130, name: "Billy Horschel", country: "US", flag: "🇺🇸" },
  { rank: 131, name: "Jhonattan Vegas", country: "VE", flag: "🇻🇪" },
  { rank: 132, name: "Steven Fisk", country: "US", flag: "🇺🇸" },
  { rank: 133, name: "Brandt Snedeker", country: "US", flag: "🇺🇸" },
  { rank: 134, name: "Laurie Canter", country: "ENG", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { rank: 135, name: "Dan Bradbury", country: "ENG", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { rank: 136, name: "William Mouw", country: "US", flag: "🇺🇸" },
  { rank: 137, name: "Davis Thompson", country: "US", flag: "🇺🇸" },
  { rank: 138, name: "Keita Nakajima", country: "JP", flag: "🇯🇵" },
  { rank: 139, name: "JC Ritchie", country: "ZA", flag: "🇿🇦" },
  { rank: 140, name: "Taylor Moore", country: "US", flag: "🇺🇸" },
  { rank: 141, name: "Nacho Elvira", country: "ES", flag: "🇪🇸" },
  { rank: 142, name: "Calum Hill", country: "SCO", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  { rank: 143, name: "Seonghyeon Kim", country: "KR", flag: "🇰🇷" },
  { rank: 144, name: "Tom Kim", country: "KR", flag: "🇰🇷" },
  { rank: 145, name: "Takumi Kanaya", country: "JP", flag: "🇯🇵" },
  { rank: 146, name: "Martin Couvra", country: "FR", flag: "🇫🇷" },
  { rank: 147, name: "Travis Smyth", country: "AU", flag: "🇦🇺" },
  { rank: 148, name: "Cameron Smith", country: "AU", flag: "🇦🇺" },
  { rank: 149, name: "Joaquin Niemann", country: "CL", flag: "🇨🇱" },
  { rank: 150, name: "Vincent Whaley", country: "US", flag: "🇺🇸" },
  { rank: 151, name: "Beau Hossler", country: "US", flag: "🇺🇸" },
  { rank: 152, name: "Mackenzie Hughes", country: "CA", flag: "🇨🇦" },
  { rank: 153, name: "Lee Hodges", country: "US", flag: "🇺🇸" },
  { rank: 154, name: "Davis Riley", country: "US", flag: "🇺🇸" },
  { rank: 155, name: "Marcus Armitage", country: "ENG", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { rank: 156, name: "Jorge Campillo", country: "ES", flag: "🇪🇸" },
  { rank: 157, name: "Kazuki Higa", country: "JP", flag: "🇯🇵" },
  { rank: 158, name: "Davis Lamb", country: "US", flag: "🇺🇸" },
  { rank: 159, name: "Zachary Bauchou", country: "US", flag: "🇺🇸" },
  { rank: 160, name: "Joe Highsmith", country: "US", flag: "🇺🇸" },
  { rank: 161, name: "Adrien Dumont de Chassart", country: "BE", flag: "🇧🇪" },
  { rank: 162, name: "Oliver Lindell", country: "FI", flag: "🇫🇮" },
  { rank: 163, name: "Chad Ramey", country: "US", flag: "🇺🇸" },
  { rank: 164, name: "Adam Schenk", country: "US", flag: "🇺🇸" },
  { rank: 165, name: "Joakim Lagergren", country: "SE", flag: "🇸🇪" },
  { rank: 166, name: "Jackson Suber", country: "US", flag: "🇺🇸" },
  { rank: 167, name: "Jeremy Gandon", country: "FR", flag: "🇫🇷" },
  { rank: 168, name: "Byeong Hun An", country: "KR", flag: "🇰🇷" },
  { rank: 169, name: "Scott Vincent", country: "ZW", flag: "🇿🇼" },
  { rank: 170, name: "Dean Burmester", country: "ZA", flag: "🇿🇦" },
  { rank: 171, name: "Austin Eckroat", country: "US", flag: "🇺🇸" },
  { rank: 172, name: "Peter Uihlein", country: "US", flag: "🇺🇸" },
  { rank: 173, name: "Kota Kaneko", country: "JP", flag: "🇯🇵" },
  { rank: 174, name: "Chandler Phillips", country: "US", flag: "🇺🇸" },
  { rank: 175, name: "Erik van Rooyen", country: "ZA", flag: "🇿🇦" },
  { rank: 176, name: "Karl Vilips", country: "AU", flag: "🇦🇺" },
  { rank: 177, name: "Julien Guerrier", country: "FR", flag: "🇫🇷" },
  { rank: 178, name: "Carson Young", country: "US", flag: "🇺🇸" },
  { rank: 179, name: "Ewen Ferguson", country: "SCO", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  { rank: 180, name: "Carlos Ortiz", country: "MX", flag: "🇲🇽" },
  { rank: 181, name: "Richard T. Lee", country: "CA", flag: "🇨🇦" },
  { rank: 182, name: "Neal Shipley", country: "US", flag: "🇺🇸" },
  { rank: 183, name: "Hennie Du Plessis", country: "ZA", flag: "🇿🇦" },
  { rank: 184, name: "Seamus Power", country: "IE", flag: "🇮🇪" },
  { rank: 185, name: "Doug Ghim", country: "US", flag: "🇺🇸" },
  { rank: 186, name: "Ding Wenyi", country: "CN", flag: "🇨🇳" },
  { rank: 187, name: "Marty Dou Zecheng", country: "CN", flag: "🇨🇳" },
  { rank: 188, name: "Jesper Svensson", country: "SE", flag: "🇸🇪" },
  { rank: 189, name: "Matt Kuchar", country: "US", flag: "🇺🇸" },
  { rank: 190, name: "Sergio Garcia", country: "ES", flag: "🇪🇸" },
  { rank: 191, name: "Anthony Kim", country: "US", flag: "🇺🇸" },
  { rank: 192, name: "Antoine Rozner", country: "FR", flag: "🇫🇷" },
  { rank: 193, name: "Alistair Docherty", country: "US", flag: "🇺🇸" },
  { rank: 194, name: "Francesco Laporta", country: "IT", flag: "🇮🇹" },
  { rank: 195, name: "Kazuma Kobori", country: "NZ", flag: "🇳🇿" },
  { rank: 196, name: "Patrick Fishburn", country: "US", flag: "🇺🇸" },
  { rank: 197, name: "Grant Forrest", country: "SCO", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  { rank: 198, name: "Victor Perez", country: "FR", flag: "🇫🇷" },
  { rank: 199, name: "Zac Blair", country: "US", flag: "🇺🇸" },
  { rank: 200, name: "Davis Bryant", country: "US", flag: "🇺🇸" },
];

export const BUCKETS = ["1-10", "11-20", "21-30", "31-40", "40+"];

export function bucketForRank(r) {
  if (r <= 10) return "1-10";
  if (r <= 20) return "11-20";
  if (r <= 30) return "21-30";
  if (r <= 40) return "31-40";
  return "40+"; // 41 through the very last ranked player
}

// Players grouped into the five buckets, in rank order.
export function playersByBucket() {
  const out = { "1-10": [], "11-20": [], "21-30": [], "31-40": [], "40+": [] };
  for (const p of OWGR_RANKINGS) out[bucketForRank(p.rank)].push(p);
  return out;
}

// Stable, name-based key used as the pick id and as the player-DB key.
export const slug = (name) =>
  (name || "").normalize("NFKD").replace(/[\u0300-\u036f]/g, "")
    .toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

// A pick object — what we store on an entry and feed to the leaderboard.
export const toPick = (p) => ({
  key: slug(p.name), name: p.name, owgr: p.rank, bucket: bucketForRank(p.rank), flag: p.flag,
});

// Player DB keyed by slug — drop-in replacement for the old hardcoded `P`.
export const OWGR_PLAYERS = Object.fromEntries(
  OWGR_RANKINGS.map((p) => [slug(p.name),
    { name: p.name, owgr: p.rank, bucket: bucketForRank(p.rank), flag: p.flag }])
);

// Dropdown options grouped by bucket, in rank order.
export function bucketOptions() {
  const g = playersByBucket();
  const out = {};
  for (const b of BUCKETS) out[b] = g[b].map(toPick);
  return out;
}
